# Generated by Django 6.1.1 on 2026-09-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_advertisement_alter_job_options_job_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Job Portal Ethiopia', max_length=100, verbose_name='የዌብሳይት ስም')),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='የዌብሳይት ሎጎ')),
                ('site_favicon', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Favicon (ትንሹ ሎጎ)')),
                ('footer_text', models.TextField(blank=True, verbose_name='የግርጌ (Footer) ፅሁፍ')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='የመገናኛ ኢሜይል')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='የመገናኛ ስልክ')),
            ],
            options={
                'verbose_name': 'Website Setting',
                'verbose_name_plural': 'Website Settings',
            },
        ),
    ]
