# Generated by Django 6.1.1 on 2026-09-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_sitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='clicks_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
