# Generated by Django 6.1.1 on 2026-09-15 07:52

import django.core.validators
from django.db import migrations, models


def create_default_legal_pages(apps, schema_editor):
    legal_page = apps.get_model('jobs', 'LegalPage')
    pages = [
        {
            'page_type': 'privacy',
            'title': 'Privacy Policy',
            'content': '<p>Job Portal Ethiopia respects your privacy. We collect only the information needed to operate this job portal, respond to enquiries, and improve your experience.</p><p>We are based in Kombolcha, Ethiopia. We do not sell personal information, and we retain contact enquiries only as long as needed to provide support.</p>',
        },
        {
            'page_type': 'about',
            'title': 'About Job Portal Ethiopia',
            'content': '<p>Job Portal Ethiopia connects job seekers with employers and opportunities across Ethiopia.</p><p>From our community in Kombolcha, we aim to make finding and sharing meaningful work clearer, faster, and more accessible.</p>',
        },
        {
            'page_type': 'contact',
            'title': 'Contact Us',
            'content': '<p>Have a question about a listing or need help using the portal? Send us a message and our team in Kombolcha will review it.</p>',
        },
        {
            'page_type': 'terms',
            'title': 'Terms and Conditions',
            'content': '<p>By using Job Portal Ethiopia, you agree to use the service lawfully and provide accurate information.</p><p>Job listings are supplied by employers. Applicants should verify listing details directly before sharing sensitive information or accepting an offer.</p>',
        },
    ]
    for page in pages:
        legal_page.objects.get_or_create(page_type=page['page_type'], defaults=page)


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_advertisement_clicks_count_advertisement_views_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('privacy', 'Privacy Policy'), ('about', 'About Us'), ('contact', 'Contact Us'), ('terms', 'Terms and Conditions')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='HTML is supported. Unsafe tags and attributes are removed before display.')),
                ('text_color', models.CharField(default='#212529', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a six-digit hexadecimal color.')])),
                ('font_size', models.PositiveSmallIntegerField(default=16, help_text='Font size in pixels (10-48).', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(48)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Legal Page',
                'verbose_name_plural': 'Legal Pages',
                'ordering': ['page_type'],
            },
        ),
        migrations.RunPython(create_default_legal_pages, migrations.RunPython.noop),
    ]
