# Generated by Django 6.1.1 on 2026-09-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_contactmessage_legalpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='reply_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='legalpage',
            name='contact_enabled',
            field=models.BooleanField(default=True, help_text='When disabled, visitors cannot submit the Contact Us form.'),
        ),
    ]
