# Generated by Django 6.1.1 on 2026-09-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_contactmessage_replied_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='hero_badge',
            field=models.CharField(default='Premium hiring platform', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_description',
            field=models.TextField(default='Discover top jobs, connect with employers, and grow your career with a smarter job search experience.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_title',
            field=models.CharField(default='Find your next opportunity', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='show_about_contact_links',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='show_footer_links',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='show_hero',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='show_language_switcher',
            field=models.BooleanField(default=True),
        ),
    ]
