# Generated by Django 6.1.1 on 2026-09-15 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_sitesetting_hero_badge_sitesetting_hero_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='background_color',
            field=models.CharField(default='#071421', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a six-digit hexadecimal color.')]),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='corner_radius',
            field=models.PositiveSmallIntegerField(default=24, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)]),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='font_family',
            field=models.CharField(default='Segoe UI, Tahoma, sans-serif', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='primary_color',
            field=models.CharField(default='#63d9ff', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a six-digit hexadecimal color.')]),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='secondary_color',
            field=models.CharField(default='#8b5cf6', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a six-digit hexadecimal color.')]),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='show_advertisements',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='show_job_stats',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='show_search_filters',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='text_color',
            field=models.CharField(default='#edf6ff', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a six-digit hexadecimal color.')]),
        ),
    ]
