# Generated by Django 6.1.1 on 2026-09-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_sitesetting_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/backgrounds/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='background_text',
            field=models.CharField(blank=True, default='Job Portal Ethiopia', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='header_text',
            field=models.CharField(blank=True, default='Job Portal Ethiopia', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='top_bar_text',
            field=models.CharField(blank=True, default='Find your next opportunity in Ethiopia', max_length=300),
        ),
    ]
