# Generated by Django 6.1.1 on 2026-09-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_sitesetting_background_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description_aa',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='description_am',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='description_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='description_es',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='description_fr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='description_om',
            field=models.TextField(blank=True),
        ),
    ]
