# Generated by Django 6.1.1 on 2026-09-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_job_description_aa_job_description_am_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalpage',
            name='content',
            field=models.TextField(help_text='Rich text / HTML content. Unsafe tags and attributes are removed before display.'),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='page_type',
            field=models.CharField(help_text='Short unique slug for this page, such as about, privacy, faq, support, or contact.', max_length=80, unique=True),
        ),
    ]
