# Generated by Django 6.1.1 on 2026-09-15 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_legalpage_content_alter_legalpage_page_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('content', models.TextField(help_text='Enter HTML content. Unsafe tags and attributes are removed before display.')),
                ('text_color', models.CharField(default='#212529', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a six-digit hexadecimal color.')])),
                ('font_size', models.PositiveSmallIntegerField(default=16, help_text='Font size in pixels (10-48).', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(48)])),
                ('placement_location', models.CharField(choices=[('header', 'Header'), ('footer', 'Footer'), ('main_body', 'Main Body')], default='main_body', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Custom Page',
                'verbose_name_plural': 'Custom Pages',
                'ordering': ['title'],
            },
        ),
    ]
