# Generated by Django 6.1.1 on 2026-09-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_custompage_alter_legalpage_page_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalpage',
            name='placement_location',
            field=models.CharField(choices=[('header', 'Header'), ('footer', 'Footer'), ('main_body', 'Main Body')], default='footer', max_length=20),
        ),
    ]
