# Generated by Django 6.1.1 on 2026-09-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_alter_legalpage_page_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompage',
            name='placement_location',
            field=models.CharField(choices=[('header', 'Header'), ('footer', 'Footer'), ('main_body', 'Main Body'), ('right_top', 'Right Top'), ('right_middle', 'Right Middle'), ('right_bottom', 'Right Bottom'), ('left_top', 'Left Top'), ('left_middle', 'Left Middle'), ('left_bottom', 'Left Bottom')], default='main_body', max_length=20),
        ),
    ]
