# Generated by Django 6.1.1 on 2026-09-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_alter_advertisement_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='display_format',
            field=models.CharField(choices=[('auto', 'Auto (recommended)'), ('banner', 'Banner image'), ('video', 'Video'), ('full_page', 'Full page'), ('html', 'HTML / AdSense')], default='auto', max_length=20),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='video_url',
            field=models.URLField(blank=True, help_text='Direct video URL for MP4/WebM content.'),
        ),
    ]
