# Generated by Django 6.1.1 on 2026-09-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_advertisement_display_format_advertisement_video_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='position',
            field=models.CharField(choices=[('auto', 'Auto Placement'), ('header', 'Header Banner'), ('sidebar', 'Sidebar Banner'), ('inside_job', 'Inside Job Details'), ('footer', 'Footer Banner'), ('right_top', 'Right Top'), ('right_middle', 'Right Middle'), ('right_bottom', 'Right Bottom'), ('left_top', 'Left Top'), ('left_middle', 'Left Middle'), ('left_bottom', 'Left Bottom')], default='header', max_length=20),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='page_type',
            field=models.CharField(help_text='Unique URL slug, such as about, privacy, faq, support, or contact.', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='background_text',
            field=models.CharField(blank=True, default='AFRI JOB ETHIOPIA', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='header_text',
            field=models.CharField(blank=True, default='AFRI JOB ETHIOPIA', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_name',
            field=models.CharField(default='AFRI JOB ETHIOPIA', max_length=100, verbose_name='የዌብሳይት ስም'),
        ),
    ]
