# Generated by Django 6.1.1 on 2026-09-17 06:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_sitesetting_contact_submit_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='admin_accent_color',
            field=models.CharField(default='#dbeafe', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a six-digit hexadecimal color.')], verbose_name='Admin accent color'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='admin_background_image',
            field=models.ImageField(blank=True, null=True, upload_to='admin/backgrounds/', verbose_name='Admin background image'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='admin_background_video',
            field=models.FileField(blank=True, help_text='Upload an MP4 or WebM video. The image is used as the fallback.', null=True, upload_to='admin/backgrounds/', verbose_name='Admin background video'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='admin_sidebar_color',
            field=models.CharField(default='#20252d', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a six-digit hexadecimal color.')], verbose_name='Admin sidebar color'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='admin_workspace_color',
            field=models.CharField(default='#f7f8fa', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a six-digit hexadecimal color.')], verbose_name='Admin workspace color'),
        ),
    ]
