# Generated by Django 6.1.1 on 2026-09-17 06:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_sitesetting_admin_accent_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='admin_workspace_color',
            field=models.CharField(default='#e7ecf1', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a six-digit hexadecimal color.')], verbose_name='Admin workspace color'),
        ),
    ]
