# Generated by Django 6.1.1 on 2026-09-17 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_alter_sitesetting_admin_workspace_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='job_paper_height',
            field=models.PositiveIntegerField(default=700, help_text='Minimum height of the public job detail paper. Use 320-2400 px.', validators=[django.core.validators.MinValueValidator(320), django.core.validators.MaxValueValidator(2400)], verbose_name='Job paper minimum height (px)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='job_paper_width',
            field=models.PositiveIntegerField(default=860, help_text='Desktop width of the public job detail paper. Use 480-1400 px.', validators=[django.core.validators.MinValueValidator(480), django.core.validators.MaxValueValidator(1400)], verbose_name='Job paper width (px)'),
        ),
    ]
