# Generated by Django 6.1.1 on 2026-09-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0025_sitesetting_job_paper_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='position',
            field=models.CharField(choices=[('auto', 'Auto Placement'), ('header', 'Header Banner'), ('sidebar', 'Sidebar Banner'), ('inside_job', 'Inside Job Details'), ('after_apply', 'After Apply Button'), ('footer', 'Footer Banner'), ('right_top', 'Right Top'), ('right_middle', 'Right Middle'), ('right_bottom', 'Right Bottom'), ('left_top', 'Left Top'), ('left_middle', 'Left Middle'), ('left_bottom', 'Left Bottom')], default='header', max_length=20),
        ),
    ]
