# Generated by Django 6.1.1 on 2026-09-17 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0026_alter_advertisement_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='job_paper_background_color',
            field=models.CharField(default='#ffffff', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a six-digit hexadecimal color.')], verbose_name='Job paper background color'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='job_paper_background_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/job-paper/', verbose_name='Job paper background image'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='job_paper_background_video',
            field=models.FileField(blank=True, help_text='Upload MP4 or WebM. The image and color remain fallbacks.', null=True, upload_to='site/job-paper/', verbose_name='Job paper background video'),
        ),
    ]
