# Generated by Django 6.1.1 on 2026-09-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0027_sitesetting_job_paper_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='admin_background_3d',
            field=models.FileField(blank=True, help_text='Upload an MP4/WebM 3D animation.', null=True, upload_to='admin/backgrounds/3d/', verbose_name='Admin 3D background video'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='admin_background_4k',
            field=models.FileField(blank=True, help_text='Upload an optimized MP4/WebM 4K video.', null=True, upload_to='admin/backgrounds/4k/', verbose_name='Admin 4K background video'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='admin_background_mode',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('3d', '3D video'), ('4k', '4K video')], default='image', max_length=10, verbose_name='Admin background mode'),
        ),
    ]
