# Generated by Django 6.1.1 on 2026-09-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0028_sitesetting_admin_background_3d_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('attachment_names', models.JSONField(blank=True, default=list)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sent email',
                'verbose_name_plural': 'Sent emails',
                'ordering': ['-sent_at'],
            },
        ),
    ]
