# Generated by Django 6.1.1 on 2026-09-18 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0029_sentemail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sentemail',
            options={'ordering': ['-sent_at'], 'verbose_name': 'Outbox email', 'verbose_name_plural': 'Outbox'},
        ),
    ]
