# Generated by Django 6.1.1 on 2026-09-18 08:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0030_alter_sentemail_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sentemail',
            options={'ordering': ['-sent_at'], 'verbose_name': 'የተላከ ኢሜይል', 'verbose_name_plural': 'የተላኩ ኢሜይሎች'},
        ),
        migrations.AlterField(
            model_name='sentemail',
            name='message',
            field=models.TextField(verbose_name='መልእክት'),
        ),
        migrations.AlterField(
            model_name='sentemail',
            name='recipient',
            field=models.EmailField(max_length=254, verbose_name='ተቀባይ'),
        ),
        migrations.AlterField(
            model_name='sentemail',
            name='sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='የተላከበት ሰዓት'),
        ),
        migrations.AlterField(
            model_name='sentemail',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='ርዕስ'),
        ),
    ]
