# Generated by Django 6.1.1 on 2026-09-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0031_alter_sentemail_options_alter_sentemail_message_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sentemail',
            options={'ordering': ['-sent_at'], 'verbose_name': 'Sent email', 'verbose_name_plural': 'Sent emails'},
        ),
        migrations.AlterField(
            model_name='sentemail',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='sentemail',
            name='recipient',
            field=models.EmailField(max_length=254, verbose_name='Recipient'),
        ),
        migrations.AlterField(
            model_name='sentemail',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='Subject'),
        ),
    ]
