# Generated by Django 6.1.1 on 2026-09-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0032_alter_sentemail_options_alter_sentemail_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompage',
            name='slug_mode',
            field=models.CharField(choices=[('auto', 'Auto-generate from title'), ('manual', 'Enter manually')], default='auto', max_length=10),
        ),
        migrations.AlterField(
            model_name='custompage',
            name='slug',
            field=models.SlugField(blank=True, max_length=80, unique=True),
        ),
    ]
