# Generated by Django 6.1.1 on 2026-09-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0033_custompage_slug_mode_alter_custompage_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='display_mode',
            field=models.CharField(choices=[('work', 'Work display'), ('list', 'List display')], default='work', max_length=10),
        ),
    ]
