# Generated by Django 6.1.1 on 2026-09-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0034_job_display_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='job_display_mode',
            field=models.CharField(choices=[('work', 'Work display'), ('list', 'List display')], default='work', max_length=10),
        ),
    ]
