# Generated by Django 6.1.1 on 2026-09-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0035_sitesetting_job_display_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='job_display_mode',
            field=models.CharField(choices=[('previous', 'Previous display'), ('work', 'Work display'), ('list', 'List display')], default='work', max_length=10),
        ),
    ]
