# Generated by Django 6.1.1 on 2026-09-18 21:15

import ckeditor.fields
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0037_blogpost_jobcategory_alter_job_display_mode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.AlterModelOptions(
            name='jobcategory',
            options={'ordering': ['name'], 'verbose_name': 'Job Category', 'verbose_name_plural': 'Job Categories'},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(blank=True, default='Admin', max_length=120),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Short summary shown on blog cards.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='accent_color',
            field=models.CharField(blank=True, default='#63d9ff', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a six-digit hexadecimal color.')]),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='icon',
            field=models.CharField(blank=True, default='fa-briefcase', help_text='Font Awesome icon class, e.g. fa-briefcase.', max_length=50),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Full article content with formatting tools.'),
        ),
        migrations.AlterField(
            model_name='job',
            name='display_mode',
            field=models.CharField(choices=[('work', 'Work display'), ('list', 'List display')], default='work', max_length=10),
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='Default', help_text='Short category description with formatting.'),
            preserve_default=False,
        ),
    ]
