# Generated by Django 6.1.1 on 2026-09-19 05:59

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def populate_job_category_ids(apps, schema_editor):
    Job = apps.get_model('jobs', 'Job')
    JobCategory = apps.get_model('jobs', 'JobCategory')

    category_cache = {}

    for job in Job.objects.exclude(category__isnull=True).exclude(category=''):
        category_name = str(job.category).strip()
        if not category_name:
            continue

        category = category_cache.get(category_name)
        if category is None:
            category = JobCategory.objects.filter(name=category_name).first()
            if category is None:
                category = JobCategory.objects.create(
                    name=category_name,
                    slug=slugify(category_name)[:80] or 'category',
                    description='',
                    icon='fa-briefcase',
                    accent_color='#63d9ff',
                    is_featured=False,
                )
            category_cache[category_name] = category

        job.category = str(category.pk)
        job.save(update_fields=['category'])


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0038_alter_blogpost_options_alter_jobcategory_options_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_job_category_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='advertisement',
            name='position',
            field=models.CharField(choices=[('auto', 'Auto Placement'), ('header', 'Header Banner'), ('sidebar', 'Sidebar Banner'), ('inside_job', 'Inside Job Details'), ('footer', 'Footer Banner'), ('right_top', 'Right Top'), ('right_middle', 'Right Middle'), ('right_bottom', 'Right Bottom'), ('left_top', 'Left Top'), ('left_middle', 'Left Middle'), ('left_bottom', 'Left Bottom')], default='header', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Select the job category.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.jobcategory'),
        ),
    ]
