
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

class Migration(migrations.Migration):
    dependencies=[('jobs','0044_dashboard_palette_controls')]
    operations=[
        migrations.AddField(model_name='job',name='source_name',field=models.CharField(blank=True,db_index=True,max_length=200)),
        migrations.AddField(model_name='job',name='source_url',field=models.URLField(blank=True,max_length=1000)),
        migrations.AddField(model_name='job',name='original_content',field=models.TextField(blank=True)),
        migrations.AddField(model_name='job',name='content_hash',field=models.CharField(blank=True,db_index=True,max_length=64)),
        migrations.AddField(model_name='job',name='normalized_title',field=models.CharField(blank=True,db_index=True,max_length=220)),
        migrations.AddField(model_name='job',name='normalized_company',field=models.CharField(blank=True,db_index=True,max_length=220)),
        migrations.AddField(model_name='job',name='normalized_location',field=models.CharField(blank=True,db_index=True,max_length=160)),
        migrations.AddField(model_name='job',name='auto_imported',field=models.BooleanField(db_index=True,default=False)),
        migrations.AddField(model_name='job',name='telegram_notification_sent_at',field=models.DateTimeField(blank=True,null=True)),
        migrations.CreateModel(name='JobSource',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=160,unique=True)),('source_type',models.CharField(choices=[('telegram','Telegram'),('website','Website')],max_length=20)),('enabled',models.BooleanField(default=True)),('interval_minutes',models.PositiveIntegerField(default=15)),('last_run_at',models.DateTimeField(blank=True,null=True)),('last_error',models.TextField(blank=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True))]),
        migrations.CreateModel(name='TelegramSource',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('channel',models.CharField(help_text='Username such as @channel or numeric channel ID.',max_length=255)),('fetch_images',models.BooleanField(default=False)),('max_messages_per_run',models.PositiveIntegerField(default=50)),('last_message_id',models.BigIntegerField(default=0)),('session_name',models.CharField(blank=True,default='afrijob',max_length=80)),('source',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='telegram_config',to='jobs.jobsource'))]),
        migrations.CreateModel(name='WebsiteSource',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('url',models.URLField(max_length=1000)),('method',models.CharField(default='GET',max_length=10)),('headers_json',models.JSONField(blank=True,default=dict)),('listing_selector',models.CharField(blank=True,help_text='CSS selector for each job card. Leave blank to treat the page as one post.',max_length=300)),('fields_json',models.JSONField(blank=True,default=dict,help_text='CSS selectors: title, company, location, description, deadline, application_url.')),('max_items_per_run',models.PositiveIntegerField(default=30)),('timeout_seconds',models.PositiveIntegerField(default=20)),('source',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='website_config',to='jobs.jobsource'))]),
        migrations.CreateModel(name='RawJobPost',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('external_id',models.CharField(blank=True,db_index=True,max_length=255)),('source_url',models.URLField(blank=True,max_length=1500)),('content',models.TextField()),('content_hash',models.CharField(db_index=True,max_length=64)),('discovered_at',models.DateTimeField(db_index=True,default=django.utils.timezone.now)),('status',models.CharField(choices=[('new','New'),('processing','Processing'),('processed','Processed'),('rejected','Rejected'),('failed','Failed'),('duplicate','Duplicate')],db_index=True,default='new',max_length=20)),('attempts',models.PositiveIntegerField(default=0)),('last_error',models.TextField(blank=True)),('processed_at',models.DateTimeField(blank=True,null=True)),('extracted_json',models.JSONField(blank=True,default=dict)),('rejection_reason',models.CharField(blank=True,max_length=500)),('created_at',models.DateTimeField(auto_now_add=True)),('job',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='raw_posts',to='jobs.job')),('source',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='raw_posts',to='jobs.jobsource'))]),
        migrations.AddConstraint(model_name='rawjobpost',constraint=models.UniqueConstraint(fields=('source','external_id'),name='uniq_raw_source_external')),
        migrations.CreateModel(name='JobProcessingLog',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('provider',models.CharField(blank=True,max_length=80)),('stage',models.CharField(choices=[('collect','Collect'),('ai','AI'),('validate','Validate'),('dedupe','Duplicate check'),('publish','Publish'),('telegram','Telegram'),('system','System')],max_length=20)),('status',models.CharField(choices=[('started','Started'),('success','Success'),('failed','Failed'),('skipped','Skipped')],max_length=20)),('message',models.TextField(blank=True)),('retry_count',models.PositiveIntegerField(default=0)),('created_at',models.DateTimeField(default=django.utils.timezone.now)),('raw_post',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.CASCADE,related_name='logs',to='jobs.rawjobpost')),('job',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='processing_logs',to='jobs.job'))]),
        migrations.CreateModel(name='TelegramNotification',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('channel_id',models.CharField(max_length=255)),('message_id',models.BigIntegerField(blank=True,null=True)),('message_text',models.TextField(blank=True)),('status',models.CharField(default='pending',max_length=20)),('attempts',models.PositiveIntegerField(default=0)),('last_error',models.TextField(blank=True)),('sent_at',models.DateTimeField(blank=True,null=True)),('created_at',models.DateTimeField(auto_now_add=True)),('job',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='telegram_notification',to='jobs.job'))]),
        migrations.CreateModel(name='AutomationRun',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('started_at',models.DateTimeField(default=django.utils.timezone.now)),('finished_at',models.DateTimeField(blank=True,null=True)),('command',models.CharField(max_length=120)),('collected',models.PositiveIntegerField(default=0)),('processed',models.PositiveIntegerField(default=0)),('published',models.PositiveIntegerField(default=0)),('rejected',models.PositiveIntegerField(default=0)),('duplicates',models.PositiveIntegerField(default=0)),('failed',models.PositiveIntegerField(default=0)),('summary',models.TextField(blank=True))]),
    ]
