# Generated by Django 6.1.1 on 2026-09-28 19:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0045_automation_system'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automationrun',
            options={'ordering': ['-started_at']},
        ),
        migrations.AlterModelOptions(
            name='jobprocessinglog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='jobsource',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='rawjobpost',
            options={'ordering': ['-discovered_at']},
        ),
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': 'Website setting', 'verbose_name_plural': 'Website settings'},
        ),
        migrations.AddField(
            model_name='job',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.jobsource'),
        ),
        migrations.AddField(
            model_name='job',
            name='telegram_destination_mode',
            field=models.CharField(choices=[('auto', 'Automatic source routing'), ('all', 'All enabled destinations'), ('selected', 'Selected destinations')], default='auto', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='apply_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='job',
            name='normalized_company',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='normalized_location',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='normalized_title',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='source_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='source_url',
            field=models.URLField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='sentemail',
            name='sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sent at'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Contact email'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Contact phone'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='footer_text',
            field=models.TextField(blank=True, verbose_name='Footer text'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_favicon',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Website favicon'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Website logo'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_name',
            field=models.CharField(default='AFRI JOB ETHIOPIA', max_length=100, verbose_name='Website name'),
        ),
        migrations.AlterField(
            model_name='telegramnotification',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_notifications', to='jobs.job'),
        ),
        migrations.CreateModel(
            name='TelegramDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('channel_id', models.CharField(help_text='Telegram channel username such as @mychannel or numeric channel ID.', max_length=255, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_sources', models.ManyToManyField(blank=True, help_text='Leave empty to allow jobs from all enabled sources.', related_name='telegram_destinations', to='jobs.jobsource')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='telegram_destinations',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='jobs.telegramdestination'),
        ),
        migrations.AddField(
            model_name='telegramnotification',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='jobs.telegramdestination'),
        ),
        migrations.AddConstraint(
            model_name='telegramnotification',
            constraint=models.UniqueConstraint(fields=('job', 'destination'), name='uniq_telegram_notification_job_destination'),
        ),
    ]
