# Generated by Django 6.1.1 on 2026-10-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0047_automationcontrol_job_country_job_education_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramdestination',
            name='filters_json',
            field=models.JSONField(blank=True, default=dict, help_text='Destination filters: organization, education, experience, employment, region, country, category, work mode, keywords, salary, etc.'),
        ),
    ]
