# Generated by Django 6.1.1 on 2026-10-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0048_telegramdestination_filters_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('days_of_week', models.JSONField(blank=True, default=list, help_text='Use weekday numbers: 0=Monday ... 6=Sunday.')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_jobs', models.PositiveIntegerField(default=5, help_text='Maximum jobs allowed during this schedule window.')),
                ('max_jobs_per_run', models.PositiveIntegerField(default=1, help_text='Maximum jobs to publish in one automation cycle.')),
                ('filters_json', models.JSONField(blank=True, default=dict, help_text='Optional country, region, organization, category, keyword and other filters.')),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('jobs_published', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destinations', models.ManyToManyField(blank=True, help_text='Leave empty to use the job destination rules.', related_name='automation_schedules', to='jobs.telegramdestination')),
            ],
            options={
                'verbose_name': 'Automation Schedule',
                'verbose_name_plural': 'Automation Schedules',
                'ordering': ['start_time', 'name'],
            },
        ),
    ]
