# Generated by Django 6.1.1 on 2026-10-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0049_automationschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationcontrol',
            name='daily_max_jobs',
            field=models.PositiveIntegerField(default=0, help_text='Maximum jobs to publish per day. 0 = unlimited.'),
        ),
    ]
