# Generated by Django 6.1.1 on 2026-10-02 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0050_automationcontrol_daily_max_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationcontrol',
            name='active_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_controls', to='jobs.automationrun'),
        ),
        migrations.AddField(
            model_name='automationrun',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='automationrun',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='queued', max_length=20),
        ),
    ]
