# Generated by Django 6.1.1 on 2026-10-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0052_telegramnotification_last_attempt_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramnotification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
