# Generated by Django 6.1.1 on 2026-10-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0053_alter_telegramnotification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience_level',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
