# Generated by Django 6.1.1 on 2026-10-04 10:35

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0054_alter_job_experience_level'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='blogpost',
                    name='content',
                    field=django_ckeditor_5.fields.CKEditor5Field(
                        help_text='Full article content with formatting tools.'
                    ),
                ),
                migrations.AlterField(
                    model_name='jobcategory',
                    name='description',
                    field=django_ckeditor_5.fields.CKEditor5Field(
                        blank=True,
                        help_text='Short category description with formatting.'
                    ),
                ),
            ],
        ),
    ]
