"""
Django settings for jopportal project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import re
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

configured_admin_url = os.environ.get('DJANGO_ADMIN_URL', 'secure-console-7f3a91').strip().strip('/')
if not re.fullmatch(r'[A-Za-z0-9_-]{8,80}', configured_admin_url):
    raise ImproperlyConfigured(
        'DJANGO_ADMIN_URL must contain 8-80 letters, numbers, underscores, or hyphens.'
    )
ADMIN_URL = f'{configured_admin_url}/'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
deployment_environment = os.environ.get('DJANGO_ENV', 'development').strip().lower()
production_environment = deployment_environment in {'production', 'prod'}
TRUE_VALUES = {'1', 'true', 'yes', 'on'}


def environment_bool(name, default=False):
    return os.environ.get(name, str(default)).strip().lower() in TRUE_VALUES


DEBUG = environment_bool('DJANGO_DEBUG', not production_environment)

FALLBACK_SECRET_KEY = (
    'dev-fallback-secret-key-for-local-use-only-change-this-before-deploy-1234567890'
)
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '').strip() or FALLBACK_SECRET_KEY

DEFAULT_ALLOWED_HOSTS = [
    'web-i4fa.onrender.com',
    'afrijob.world',
    'www.afrijob.world',
    'localhost',
    '127.0.0.1',
]
ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('DJANGO_ALLOWED_HOSTS', ','.join(DEFAULT_ALLOWED_HOSTS)).split(',')
    if host.strip()
]
if not ALLOWED_HOSTS:
    raise ImproperlyConfigured('DJANGO_ALLOWED_HOSTS must contain at least one hostname.')

LANGUAGE_CODE = 'en-us'

LANGUAGES = [
    ('en', 'English'),
    ('am', 'አማርኛ'),
    ('aa', 'Afaraf'),
    ('ar', 'العربية'),
    ('es', 'Español'),
    ('fr', 'Français'),
    ('om', 'Afaan Oromoo'),
]

# Django's admin language chooser needs display metadata for Amharic.
from django.conf.locale import LANG_INFO

LANG_INFO.update({
    'am': {'bidi': False, 'code': 'am', 'name': 'Amharic', 'name_local': 'አማርኛ'},
    'aa': {'bidi': False, 'code': 'aa', 'name': 'Afar', 'name_local': 'Afaraf'},
    'om': {'bidi': False, 'code': 'om', 'name': 'Oromo', 'name_local': 'Afaan Oromoo'},
})

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'ckeditor',
    'ckeditor_uploader',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'jobs',
]

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 220,
        'width': '100%',
        'extraPlugins': 'image2,uploadimage',
        'removePlugins': 'stylesheetparser,image',
        'filebrowserUploadUrl': '/ckeditor/upload/',
        'filebrowserBrowseUrl': '/ckeditor/browse/',
        'image2_alignClasses': ['image-align-left', 'image-align-center', 'image-align-right'],
        'image2_disableResizer': False,
    }
}
CKEDITOR_UPLOAD_PATH = 'uploads/'
CKEDITOR_ALLOW_NONIMAGE_FILES = False

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'jopportal.middleware.SecurityHeadersMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'jopportal.middleware.RateLimitMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Limits are intentionally configurable so production deployments can tune them
# without changing application code. Use a shared cache backend across workers.
RATE_LIMITS = {
    'admin_login': {'limit': 10, 'window': 300},
    'contact': {'limit': 5, 'window': 600},
    'search': {'limit': 60, 'window': 60},
    'api': {'limit': 60, 'window': 60},
    'upload': {'limit': 20, 'window': 60},
    'account': {'limit': 10, 'window': 300},
}
RATE_LIMIT_TRUST_X_FORWARDED_FOR = os.environ.get(
    'DJANGO_RATE_LIMIT_TRUST_X_FORWARDED_FOR', 'False'
).lower() in {'1', 'true', 'yes'}
AUTH_LOGIN_FAILURE_LIMIT = int(os.environ.get('DJANGO_AUTH_LOGIN_FAILURE_LIMIT', '5'))
AUTH_LOGIN_FAILURE_WINDOW = int(os.environ.get('DJANGO_AUTH_LOGIN_FAILURE_WINDOW', '900'))
AUTH_LOGIN_BLOCK_DURATION = int(os.environ.get('DJANGO_AUTH_LOGIN_BLOCK_DURATION', '900'))
LOGIN_URL = f'/{ADMIN_URL.strip("/")}/login/'
LOGIN_REDIRECT_URL = f'/{ADMIN_URL.strip("/")}/'
cache_location = os.environ.get('DJANGO_CACHE_URL', '').strip()
CACHES = {
    'default': {
        'BACKEND': (
            'django.core.cache.backends.redis.RedisCache'
            if cache_location
            else 'django.core.cache.backends.locmem.LocMemCache'
        ),
        'LOCATION': cache_location or 'jopportal-rate-limit',
    },
}

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        'DJANGO_CSRF_TRUSTED_ORIGINS',
        'http://localhost,http://127.0.0.1,http://testserver,'
        'https://localhost,https://127.0.0.1,https://testserver,'
        'https://afrijob.world,https://www.afrijob.world,'
        'https://web-i4fa.onrender.com'
    ).split(',')
    if origin.strip()
]

# HTTPS is opt-in. If you do not run this site behind TLS, keep it disabled.
SECURE_SSL_REDIRECT = environment_bool('DJANGO_SECURE_SSL_REDIRECT', False)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_COOKIES = environment_bool('DJANGO_SECURE_COOKIES', False)
SESSION_COOKIE_SECURE = SECURE_COOKIES and SECURE_SSL_REDIRECT
CSRF_COOKIE_SECURE = SECURE_COOKIES and SECURE_SSL_REDIRECT
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
SECURE_CONTENT_TYPE_NOSNIFF = True
CONTENT_SECURITY_POLICY = (
    "default-src 'self'; "
    "base-uri 'self'; object-src 'none'; frame-ancestors 'none'; form-action 'self'; "
    "script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://pagead2.googlesyndication.com "
    "https://googleads.g.doubleclick.net; "
    "style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com; "
    "img-src 'self' data: blob: https:; font-src 'self' data: https://cdnjs.cloudflare.com https://cdn.jsdelivr.net; "
    "media-src 'self' https:; frame-src 'self' https://googleads.g.doubleclick.net; connect-src 'self'"
)
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
SECURE_HSTS_SECONDS = int(os.environ.get(
    'DJANGO_SECURE_HSTS_SECONDS', '0'
))
SECURE_HSTS_INCLUDE_SUBDOMAINS = environment_bool('DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS')
SECURE_HSTS_PRELOAD = environment_bool('DJANGO_SECURE_HSTS_PRELOAD')

ROOT_URLCONF = 'jopportal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'jobs.context_processors.global_context',
                'jobs.context_processors.admin_language_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'jopportal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL'),
        conn_max_age=int(os.environ.get('DJANGO_DB_CONN_MAX_AGE', '60')),
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 12},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']
# Use a non-manifested static backend in non-debug mode so the app can still boot and
# render templates when the compressed manifest has not been generated yet.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': (
            'django.contrib.staticfiles.storage.StaticFilesStorage'
            if DEBUG
            else 'whitenoise.storage.CompressedStaticFilesStorage'
        ),
    },
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

email_username = os.environ.get('DJANGO_EMAIL_HOST_USER', 'afrijobethiopia@gmail.com').strip()
email_password = os.environ.get('DJANGO_EMAIL_HOST_PASSWORD', '').strip()
default_mailer_backend = (
    'django.core.mail.backends.smtp.EmailBackend'
    if email_password
    else 'django.core.mail.backends.filebased.EmailBackend' if DEBUG
    else 'django.core.mail.backends.smtp.EmailBackend'
)
MAILER_BACKEND = os.environ.get('DJANGO_EMAIL_BACKEND', default_mailer_backend)
MAILER_OPTIONS = {
    'file_path': str(BASE_DIR / 'sent_emails'),
}
if MAILER_BACKEND.endswith('smtp.EmailBackend'):
    MAILER_OPTIONS = {
        'host': os.environ.get('DJANGO_EMAIL_HOST', 'smtp.gmail.com').strip(),
        'port': int(os.environ.get('DJANGO_EMAIL_PORT', '587').strip()),
        'username': email_username,
        'password': email_password,
        'use_tls': os.environ.get('DJANGO_EMAIL_USE_TLS', 'True').strip().lower() in {'1', 'true', 'yes'},
    }

MAILERS = {
    'default': {
        'BACKEND': MAILER_BACKEND,
        'OPTIONS': MAILER_OPTIONS,
    },
}
DEFAULT_FROM_EMAIL = os.environ.get(
    'DJANGO_DEFAULT_FROM_EMAIL',
    'afrijobethiopia@gmail.com',
).strip()
import os

# Media Files Configuration (ለCompany Logo እና ማስታወቂያዎች)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
ADVERTISEMENT_ALLOWED_HOSTS = {
    host.strip().lower()
    for host in os.environ.get('DJANGO_ADVERTISEMENT_ALLOWED_HOSTS', 'docs.google.com').split(',')
    if host.strip()
}

# Jazzmin Admin Dashboard Configuration
JAZZMIN_SETTINGS = {
    "site_title": "AFRI JOB ETHIOPIA Admin",
    "site_header": "AFRI JOB ETHIOPIA",
    "site_brand": "AFRI JOB ETHIOPIA Admin",
    "welcome_sign": "Welcome to AFRI JOB ETHIOPIA Administration",
    "copyright": "AFRI JOB ETHIOPIA",
    "search_model": "jobs.Job",
    "show_ui_builder": False,
    "language_chooser": True,
    "dark_mode_theme": "light",
    "default_theme_mode": "light",
    "changeform_format": "horizontal_tabs",
    "custom_css": "admin_theme.css",
    "custom_js": "js/admin_3d.js",
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-info",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "sidebar": "sidebar-dark",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    "theme": "flatly",
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}
